### ISSUE TITLE
Not scrolling on mobile devices on Chrome

### ISSUE THREAD

**Issue by GabrielmLinassi** [Emiliano-Bucci/react-spring-carousel-js#10]
For desktop screen, works fine but on mobile it doesn't scroll. I tested on Firefox, works fine, but for chrome on mobile screens doesn't. Does anybody else has the same issue?

**Comment by Emiliano-Bucci** [comment]
Hi! Could you please try to add `touch-action: none` to your carousel items?

**Comment by GabrielmLinassi** [comment]
Thanks, @Emiliano-Bucci. It's now fixed

**Comment by BesavedTech** [comment]
I am experiencing this issue as well when I set the height of the wrapper to take full height.
