### ISSUE TITLE
getIsDragging should reset to false when dragging is complete.

### ISSUE THREAD

**Issue by chakafasano88** [Emiliano-Bucci/react-spring-carousel-js#2]
Love the carousel, great work! I am experiencing an issue withh `getIsDragging()`. Initially, its value is false.  I go to slide, it sets to true, however it does not reset to false.  I see in the source code on line 136 of `useSpringCarousel.tsx` it is setting to false but it is not reflected in my example.  Here is my use case: 

```import React, { useMemo, useState, useContext } from 'react'

import PropTypes from 'prop-types'
import classNames from 'classnames'

import CardMedia from '../card-media/card-media.component'
import SliderDot from '../slider-dot/slider-dot.component'

import { useSpringCarousel } from 'react-spring-carousel-js'

import useStyles from './card-media-container.style'


const CardMediaContainer = (props) => {
  const { media, className } = props
  
  const [activeSlideIndex, setActiveSlideIndex] = useState(0)

  const {
    carouselFragment,
    useListenToCustomEvent,
    slideToItem,
    getIsDragging,
  } = useSpringCarousel({
    initialActiveItem: 0,
    items: media.map((item, i) => ({
      id: i,
      renderItem: (
        <CardMedia
          key={item.url}
          isActive={activeSlideIndex === i}
          // getIsDragging={() => getIsDragging()}
          media={item}
        />
      )
    }))
  })

  const dragging = getIsDragging()

  const classes = useStyles(props)

  const getClasses = useMemo(() => {
    const cardMediaContainerClasses = [classes.baseCardMediaSlider]

    return classNames(cardMediaContainerClasses, { [className]: !!className })
  }, [className, classes.baseCardMediaSlider])
  
  const handleOnClick = (_, index) => slideToItem(index)

  useListenToCustomEvent('onSlideStartChange', ({ nextItem }) => setActiveSlideIndex(nextItem))

  if (!media) return

  return (
    <div className={getClasses}>
      <div>{carouselFragment}</div>
      <div className={classes.container}>
        <div className={classes.dots}>
          {media.length > 1 && media.map((_, i) => <SliderDot
            key={i}
            className={classes.dot}
            index={i}
            isActive={activeSlideIndex === i}
            onClick={handleOnClick}
          />)}
        </div>
      </div>
    </div>
  )
}

CardMediaContainer.defaultProps = {
  className: '',
  media: []
}

CardMediaContainer.propTypes = {
  className: PropTypes.string,
  media: PropTypes.arrayOf(PropTypes.shape({}))
}

export default CardMediaContainer

**Comment by wildtrek** [comment]
@chakafasano88 Hi, thanks for using the library and for the feedback, it's much appreciated :) I'll take a look asap and will back to you.

**Comment by Emiliano-Bucci** [comment]
@chakafasano88  Hi, thanks for using the library and for the feedback, it's very appreciated :) I'll take a look asap and will back to you.

**Comment by chakafasano88** [comment]
> @chakafasano88 Hi, thanks for using the library and for the feedback, it's very appreciated :) I'll take a look and i'll back to you asap.

Thank you! I could be using the functionality incorrectly.  If I log ```getIsDragging()``` like this:

```  useListenToCustomEvent('onSlideStartChange', ({ nextItem }) => console.log('onSlideStartChange', getIsDragging()))
  useListenToCustomEvent('onSlideChange', ({ nextItem }) => console.log('onSlideChange', getIsDragging()))```

**Comment by chakafasano88** [comment]
> @chakafasano88 Hi, thanks for using the library and for the feedback, it's very appreciated :) I'll take a look and i'll back to you asap.

I was using incorrectly.... according to your GitHub, documentation: 

`The following options and API can be both extracted from the main hook or from the own Carousel Context (that can be imported and used inside any component rendered inside the Carousel 😏)`

I'm using `useContext` now inside the carousel and everything behaves accordingly.

**Comment by Emiliano-Bucci** [comment]
@chakafasano88 Great! Still, could you please explain me better this: 
```
However, I am triggering state changes inside onSlideStartChange and I have noticed a
different issue where only one hook fires and others don't. If I remove the state change and just console log the events, they fire correctly.
```

**Comment by Emiliano-Bucci** [comment]
@chakafasano88 I've just release a small update - `1.2.0` which fix the issues you've spotted when doing some state update in the same component when the `carouselFragment` is used. While I strongly suggest to move the carousel component logic (for example to update his styles) inside the component (just for performances reasons), you can now correctly use it and events will fire correctly.

As a last point, I've also introduce a small improvement in the use of the context, please read here -> https://github.com/Emiliano-Bucci/react-spring-carousel-js/releases/tag/1.2.0.

I'll close the issue; if you need any other help, don't esitate to reach me out!
