### ISSUE TITLE
Force resize on fullscreen change

### ISSUE THREAD

**Issue by robheritage** [Emiliano-Bucci/react-spring-carousel-js#21]
Hi, I am having an issue where the slides move out of sync when toggling fullscreen mode. This happens when the carousel does not fill the window's width, e.g. it is within a fixed width container on the page and then when in fullscreen mode, it does fill the window width. My guess is because `handleResize` does not proceed due to the window's width being the same as before? If I resize the window it obviously then all comes back in to sync with the correct slide selected.

Is there a way to force a resize when toggling fullscreen mode?

**Comment by robheritage** [comment]
A little more on this. It looks like the problem lies with the `use-spring-carousel-animated-wrapper` container styles. When entering fullscreen the `left` CSS property is updated, but the `translate3d` property is not:

Before fullscreen:
![image](https://user-images.githubusercontent.com/3169195/147107256-a461f41c-725d-4564-a475-983e0747ede2.png)

Fullscreen:
![image](https://user-images.githubusercontent.com/3169195/147107350-e12446c6-77ce-4028-95eb-ba7cf516c0d0.png)

**Comment by Emiliano-Bucci** [comment]
@robheritage Hi! I see; i will check, but i believe i've already fix this issue in the version 2 i'm ready to release before the end of the year :) I'll let you know when it will be release. Thanks!

**Comment by robheritage** [comment]
> @robheritage Hi! I see; i will check, but i believe i've already fix this issue in the version 2 i'm ready to release before the end of the year :) I'll let you know when it will be release. Thanks!

Perfect, looking forward to the release.

**Comment by Emiliano-Bucci** [comment]
@robheritage Hi! Version 2 has been released -> https://react-spring-carousel.emilianobucci.com/ Please check if the issue was fixed :)
