### ISSUE TITLE
Is there a possibility to set a gap between slides?

### ISSUE THREAD

**Issue by lucax88x** [Emiliano-Bucci/react-spring-carousel-js#22]
This is helpful expecially when you have more than one slide and you want to define some margin between them

**Comment by Emiliano-Bucci** [comment]
@lucax88x Hi! Currently no, but it'll be available in version 2 of the library. As soon as it will be available, i'll also notify here :)

**Comment by Emiliano-Bucci** [comment]
@lucax88x Hello, and sorry for the delay! Now is possible in the new version of the carousel -> https://react-spring-carousel.emilianobucci.com/docs/use-spring-carousel/multiple-items :)
