### ISSUE TITLE
Is it possible to set how many slides to slide?

### ISSUE THREAD

**Issue by IShinkarenko** [Emiliano-Bucci/react-spring-carousel-js#23]
Hi!
Currently it's possible to slide slides one by one.
Can it be 2,3 or more slides per click.
Thank you!

**Comment by Emiliano-Bucci** [comment]
@IShinkarenko Hi, sorry for the delay! Is now possible in the new version of the library -> https://react-spring-carousel.emilianobucci.com/. If you have any other issues, please open a new issue in the new repo. Thanks! :)
