### ISSUE TITLE
Disable Gesture Handler

### ISSUE THREAD

**Issue by lagmoellertim** [Emiliano-Bucci/react-spring-carousel-js#3]
Hey,
first of all, thank you for your awesome library! I am planning to use it in my current Image Gallery Project inside of a custom Lightbox. I would like to build in a zoom-feature (double tap on pcs, pinch to zoom on mobile). I think that it would be useful to add the ability to disable the gesture handlers of this carousel (so it just displays the current image/slide), so that other gesture handlers like zoom can take over, until you zoom back to normal, in which case the carousel gesture handlers could be activated again.

So maybe a additional prop like disableGestures could be implemented.

**Comment by Emiliano-Bucci** [comment]
@lagmoellertim Hello! And thanks for the feedback :) I believe it could be easily done; I'll let you know :)

**Comment by Emiliano-Bucci** [comment]
@lagmoellertim Feature added -> https://github.com/Emiliano-Bucci/react-spring-carousel-js/releases/tag/v1.2.1
