### ISSUE TITLE
'CarouselItem' is not defined

### ISSUE THREAD

**Issue by amenks** [Emiliano-Bucci/react-spring-carousel-js#5]
Hi,

Following the examples from the documentation page I am having errors in components that are not being imported like CarouselItem, PlaygroundWrapper, ThumbItem and ThumbsWrapper.

**Comment by Emiliano-Bucci** [comment]
@amenks Hi! Those components are not part of my library; the ones I use in the documentation page are only there for demo purposes, but is up to the developer to implement your own components :)

**Comment by amenks** [comment]
Thank you!
